# version: '3.8'

# services:
#   springbootapp:
#     build:
#       context: ./E-Commerce
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     depends_on:
#       - mysql

#   mysql:
#     image: mysql:latest
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: your_datrootabase_name




version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_DATABASE: pharmacy
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306
    volumes:
      - ./mysql-data:/var/lib/mysql    
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./secuirtyproject
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:  
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/pharmacy
      - spring.datasource.username=root
      - spring.datasource.password=1234
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      springboot-mysql-net:
    restart: on-failure

 


networks:
  springboot-mysql-net:      